package httpserver

import (
	"log/slog"
	"net/http"

	"litewaf-api/internal/app"
)

func registerRoutes(mux *http.ServeMux, logger *slog.Logger, application *app.App) {
	handlers := newHandlers(logger, application)

	mux.HandleFunc("GET /healthz", handlers.healthz)
	mux.HandleFunc("GET /metrics", handlers.metrics)
	mux.HandleFunc("GET /api/v1/version", handlers.version)
	mux.HandleFunc("POST /api/v1/auth/login", handlers.login)

	mux.HandleFunc("GET /api/v1/applications", handlers.require(permissionRead, handlers.listApplications))
	mux.HandleFunc("POST /api/v1/applications", handlers.require(permissionWrite, handlers.createApplication))
	mux.HandleFunc("GET /api/v1/applications/{id}", handlers.require(permissionRead, handlers.getApplication))
	mux.HandleFunc("PUT /api/v1/applications/{id}", handlers.require(permissionWrite, handlers.updateApplication))
	mux.HandleFunc("DELETE /api/v1/applications/{id}", handlers.require(permissionWrite, handlers.deleteApplication))
	mux.HandleFunc("GET /api/v1/certificates", handlers.require(permissionRead, handlers.listCertificates))
	mux.HandleFunc("POST /api/v1/certificates", handlers.require(permissionWrite, handlers.createCertificate))
	mux.HandleFunc("POST /api/v1/certificates/validate", handlers.require(permissionWrite, handlers.validateCertificate))
	mux.HandleFunc("GET /api/v1/certificates/{id}", handlers.require(permissionRead, handlers.getCertificate))
	mux.HandleFunc("DELETE /api/v1/certificates/{id}", handlers.require(permissionWrite, handlers.deleteCertificate))

	mux.HandleFunc("GET /api/v1/rules", handlers.require(permissionRead, handlers.listRules))
	mux.HandleFunc("POST /api/v1/rules", handlers.require(permissionWrite, handlers.createRule))
	mux.HandleFunc("GET /api/v1/rules/{id}", handlers.require(permissionRead, handlers.getRule))
	mux.HandleFunc("PUT /api/v1/rules/{id}", handlers.require(permissionWrite, handlers.updateRule))
	mux.HandleFunc("DELETE /api/v1/rules/{id}", handlers.require(permissionWrite, handlers.deleteRule))
	mux.HandleFunc("POST /api/v1/rules/test", handlers.require(permissionWrite, handlers.testRule))

	mux.HandleFunc("GET /api/v1/rule-packages", handlers.require(permissionRead, handlers.listRulePackages))
	mux.HandleFunc("POST /api/v1/rule-packages/preview", handlers.require(permissionWrite, handlers.previewRulePackage))
	mux.HandleFunc("POST /api/v1/rule-packages/import", handlers.require(permissionWrite, handlers.importRulePackage))
	mux.HandleFunc("GET /api/v1/rule-packages/{id}", handlers.require(permissionRead, handlers.getRulePackage))
	mux.HandleFunc("DELETE /api/v1/rule-packages/{id}", handlers.require(permissionWrite, handlers.deleteRulePackage))
	mux.HandleFunc("GET /api/v1/rule-community/catalogs", handlers.require(permissionRead, handlers.listRuleCatalogs))
	mux.HandleFunc("POST /api/v1/rule-community/catalogs", handlers.require(permissionWrite, handlers.createRuleCatalog))
	mux.HandleFunc("GET /api/v1/rule-community/catalogs/{id}", handlers.require(permissionRead, handlers.getRuleCatalog))
	mux.HandleFunc("PUT /api/v1/rule-community/catalogs/{id}", handlers.require(permissionWrite, handlers.updateRuleCatalog))
	mux.HandleFunc("DELETE /api/v1/rule-community/catalogs/{id}", handlers.require(permissionWrite, handlers.deleteRuleCatalog))
	mux.HandleFunc("POST /api/v1/rule-community/catalogs/{id}/sync", handlers.require(permissionWrite, handlers.syncRuleCatalog))
	mux.HandleFunc("GET /api/v1/rule-community/catalogs/{id}/packages", handlers.require(permissionRead, handlers.listRuleCatalogPackages))
	mux.HandleFunc("POST /api/v1/rule-community/catalogs/{id}/packages/{package_id}/preview", handlers.require(permissionWrite, handlers.previewRemoteRulePackage))
	mux.HandleFunc("POST /api/v1/rule-community/catalogs/{id}/packages/{package_id}/update-preview", handlers.require(permissionWrite, handlers.previewRulePackageUpdate))
	mux.HandleFunc("POST /api/v1/rule-community/catalogs/{id}/packages/{package_id}/apply-update", handlers.require(permissionWrite, handlers.applyRulePackageUpdate))
	mux.HandleFunc("GET /api/v1/rule-community/trust-keys", handlers.require(permissionRead, handlers.listRuleTrustKeys))
	mux.HandleFunc("POST /api/v1/rule-community/trust-keys", handlers.require(permissionWrite, handlers.createRuleTrustKey))
	mux.HandleFunc("PUT /api/v1/rule-community/trust-keys/{id}", handlers.require(permissionWrite, handlers.updateRuleTrustKey))
	mux.HandleFunc("GET /api/v1/rule-community/providers", handlers.require(permissionRead, handlers.listRuleProviders))
	mux.HandleFunc("POST /api/v1/rule-community/providers", handlers.require(permissionWrite, handlers.createRuleProvider))
	mux.HandleFunc("GET /api/v1/rule-community/providers/{id}", handlers.require(permissionRead, handlers.getRuleProvider))
	mux.HandleFunc("PUT /api/v1/rule-community/providers/{id}", handlers.require(permissionWrite, handlers.updateRuleProvider))
	mux.HandleFunc("DELETE /api/v1/rule-community/providers/{id}", handlers.require(permissionWrite, handlers.deleteRuleProvider))
	mux.HandleFunc("POST /api/v1/rule-community/providers/{id}/validate", handlers.require(permissionWrite, handlers.validateRuleProvider))
	mux.HandleFunc("POST /api/v1/rule-community/providers/{id}/sync", handlers.require(permissionWrite, handlers.syncRuleProvider))
	mux.HandleFunc("POST /api/v1/rule-community/providers/{id}/retry", handlers.require(permissionWrite, handlers.retryRuleProvider))
	mux.HandleFunc("GET /api/v1/rule-community/providers/{id}/packages", handlers.require(permissionRead, handlers.listRuleProviderPackages))
	mux.HandleFunc("POST /api/v1/rule-community/providers/{id}/packages/{package_id}/preview", handlers.require(permissionWrite, handlers.previewRuleProviderPackage))
	mux.HandleFunc("POST /api/v1/rule-community/providers/{id}/packages/{package_id}/import", handlers.require(permissionWrite, handlers.importRuleProviderPackage))
	mux.HandleFunc("POST /api/v1/rule-community/export/preview", handlers.require(permissionWrite, handlers.previewRulePackageExport))
	mux.HandleFunc("POST /api/v1/rule-community/export", handlers.require(permissionWrite, handlers.exportRulePackage))
	mux.HandleFunc("GET /api/v1/rule-community/account-sources", handlers.require(permissionRead, handlers.listRuleAccountSources))
	mux.HandleFunc("POST /api/v1/rule-community/account-sources", handlers.require(permissionWrite, handlers.createRuleAccountSource))
	mux.HandleFunc("GET /api/v1/rule-community/account-sources/{id}", handlers.require(permissionRead, handlers.getRuleAccountSource))
	mux.HandleFunc("PUT /api/v1/rule-community/account-sources/{id}", handlers.require(permissionWrite, handlers.updateRuleAccountSource))
	mux.HandleFunc("DELETE /api/v1/rule-community/account-sources/{id}", handlers.require(permissionWrite, handlers.deleteRuleAccountSource))
	mux.HandleFunc("POST /api/v1/rule-community/account-sources/{id}/refresh", handlers.require(permissionWrite, handlers.refreshRuleAccountSource))
	mux.HandleFunc("GET /api/v1/rule-community/contribution-targets", handlers.require(permissionRead, handlers.listRuleContributionTargets))
	mux.HandleFunc("POST /api/v1/rule-community/contribution-targets", handlers.require(permissionWrite, handlers.createRuleContributionTarget))
	mux.HandleFunc("GET /api/v1/rule-community/contribution-pushes", handlers.require(permissionRead, handlers.listRuleContributionPushes))
	mux.HandleFunc("POST /api/v1/rule-community/contribution-pushes/preview", handlers.require(permissionWrite, handlers.previewRuleContributionPush))
	mux.HandleFunc("POST /api/v1/rule-community/contribution-pushes", handlers.require(permissionWrite, handlers.executeRuleContributionPush))
	mux.HandleFunc("GET /api/v1/rule-community/review-queue", handlers.require(permissionRead, handlers.listRuleReviewQueue))
	mux.HandleFunc("PUT /api/v1/rule-community/review-queue/{id}", handlers.require(permissionWrite, handlers.decideRuleReviewQueueItem))
	mux.HandleFunc("GET /api/v1/rule-community/feedback", handlers.require(permissionRead, handlers.listRuleFeedback))
	mux.HandleFunc("POST /api/v1/rule-community/feedback", handlers.require(permissionWrite, handlers.createRuleFeedback))
	mux.HandleFunc("GET /api/v1/rule-community/feedback-suggestions", handlers.require(permissionRead, handlers.listRuleFeedbackSuggestions))
	mux.HandleFunc("POST /api/v1/rule-community/feedback-suggestions/{id}/test", handlers.require(permissionWrite, handlers.testRuleFeedbackSuggestion))
	mux.HandleFunc("PUT /api/v1/rule-community/feedback-suggestions/{id}", handlers.require(permissionWrite, handlers.decideRuleFeedbackSuggestion))

	mux.HandleFunc("GET /api/v1/policies", handlers.require(permissionRead, handlers.listPolicies))
	mux.HandleFunc("POST /api/v1/policies", handlers.require(permissionWrite, handlers.createPolicy))
	mux.HandleFunc("GET /api/v1/policies/{id}", handlers.require(permissionRead, handlers.getPolicy))
	mux.HandleFunc("PUT /api/v1/policies/{id}", handlers.require(permissionWrite, handlers.updatePolicy))
	mux.HandleFunc("DELETE /api/v1/policies/{id}", handlers.require(permissionWrite, handlers.deletePolicy))

	mux.HandleFunc("POST /api/v1/ingest/access-logs", handlers.requireGatewayIngestion(handlers.ingestAccessLog))
	mux.HandleFunc("POST /api/v1/ingest/waf-events", handlers.requireGatewayIngestion(handlers.ingestWAFEvent))
	mux.HandleFunc("GET /api/v1/access-logs", handlers.require(permissionRead, handlers.listAccessLogs))
	mux.HandleFunc("GET /api/v1/blocked-rejected-records", handlers.require(permissionRead, handlers.listDeniedRecords))
	mux.HandleFunc("GET /api/v1/attack-logs", handlers.require(permissionRead, handlers.listAttackLogs))
	mux.HandleFunc("GET /api/v1/observability/summary", handlers.require(permissionRead, handlers.observabilitySummary))
	mux.HandleFunc("GET /api/v1/reports/statistics", handlers.require(permissionRead, handlers.statisticsReport))
	mux.HandleFunc("GET /api/v1/dynamic-bans", handlers.require(permissionRead, handlers.listDynamicBans))
	mux.HandleFunc("POST /api/v1/dynamic-bans/unban", handlers.require(permissionWrite, handlers.clearDynamicBan))
	mux.HandleFunc("GET /api/v1/dynamic-bans/clears", handlers.requireGatewayIngestion(handlers.listDynamicBanClears))
	mux.HandleFunc("GET /api/v1/protection/overview", handlers.require(permissionRead, handlers.protectionOverview))
	mux.HandleFunc("GET /api/v1/protection/migration-health", handlers.require(permissionRead, handlers.protectionRuleMigrationHealth))
	mux.HandleFunc("GET /api/v1/releases", handlers.require(permissionRead, handlers.listReleases))
	mux.HandleFunc("POST /api/v1/releases", handlers.require(permissionPublish, handlers.createRelease))
	mux.HandleFunc("GET /api/v1/releases/preview", handlers.require(permissionPublish, handlers.previewRelease))
	mux.HandleFunc("POST /api/v1/releases/{version}/rollback", handlers.require(permissionPublish, handlers.rollbackRelease))
	mux.HandleFunc("GET /api/v1/nginx-config", handlers.require(permissionRead, handlers.getNginxConfigDraft))
	mux.HandleFunc("PUT /api/v1/nginx-config", handlers.require(permissionWrite, handlers.updateNginxConfigDraft))
	mux.HandleFunc("POST /api/v1/nginx-config/validate", handlers.require(permissionWrite, handlers.validateNginxConfigDraft))

	mux.HandleFunc("GET /api/v1/audit-logs", handlers.require(permissionAudit, handlers.listAuditLogs))

	mux.HandleFunc("GET /api/v1/ip-access-lists", handlers.require(permissionRead, handlers.listIPAccessLists))
	mux.HandleFunc("POST /api/v1/ip-access-lists", handlers.require(permissionWrite, handlers.createIPAccessList))
	mux.HandleFunc("GET /api/v1/ip-access-lists/{id}", handlers.require(permissionRead, handlers.getIPAccessList))
	mux.HandleFunc("PUT /api/v1/ip-access-lists/{id}", handlers.require(permissionWrite, handlers.updateIPAccessList))
	mux.HandleFunc("DELETE /api/v1/ip-access-lists/{id}", handlers.require(permissionWrite, handlers.deleteIPAccessList))

	mux.HandleFunc("GET /api/v1/access-control/rules", handlers.require(permissionRead, handlers.listAccessControlRules))
	mux.HandleFunc("POST /api/v1/access-control/rules", handlers.require(permissionWrite, handlers.createAccessControlRule))
	mux.HandleFunc("GET /api/v1/access-control/rules/{id}", handlers.require(permissionRead, handlers.getAccessControlRule))
	mux.HandleFunc("PUT /api/v1/access-control/rules/{id}", handlers.require(permissionWrite, handlers.updateAccessControlRule))
	mux.HandleFunc("DELETE /api/v1/access-control/rules/{id}", handlers.require(permissionWrite, handlers.deleteAccessControlRule))

	mux.HandleFunc("GET /api/v1/rate-limits", handlers.require(permissionRead, handlers.listRateLimits))
	mux.HandleFunc("POST /api/v1/rate-limits", handlers.require(permissionWrite, handlers.createRateLimit))
	mux.HandleFunc("GET /api/v1/rate-limits/{id}", handlers.require(permissionRead, handlers.getRateLimit))
	mux.HandleFunc("PUT /api/v1/rate-limits/{id}", handlers.require(permissionWrite, handlers.updateRateLimit))
	mux.HandleFunc("DELETE /api/v1/rate-limits/{id}", handlers.require(permissionWrite, handlers.deleteRateLimit))

	mux.HandleFunc("GET /api/v1/cc-protection/rules", handlers.require(permissionRead, handlers.listCCProtectionRules))
	mux.HandleFunc("POST /api/v1/cc-protection/rules", handlers.require(permissionWrite, handlers.createCCProtectionRule))
	mux.HandleFunc("POST /api/v1/cc-protection/preview", handlers.require(permissionRead, handlers.previewCCProtection))
	mux.HandleFunc("GET /api/v1/cc-protection/rules/{id}", handlers.require(permissionRead, handlers.getCCProtectionRule))
	mux.HandleFunc("PUT /api/v1/cc-protection/rules/{id}", handlers.require(permissionWrite, handlers.updateCCProtectionRule))
	mux.HandleFunc("DELETE /api/v1/cc-protection/rules/{id}", handlers.require(permissionWrite, handlers.deleteCCProtectionRule))

	mux.HandleFunc("GET /api/v1/upload-protection/rules", handlers.require(permissionRead, handlers.listUploadProtectionRules))
	mux.HandleFunc("POST /api/v1/upload-protection/rules", handlers.require(permissionWrite, handlers.createUploadProtectionRule))
	mux.HandleFunc("GET /api/v1/upload-protection/rules/{id}", handlers.require(permissionRead, handlers.getUploadProtectionRule))
	mux.HandleFunc("PUT /api/v1/upload-protection/rules/{id}", handlers.require(permissionWrite, handlers.updateUploadProtectionRule))
	mux.HandleFunc("DELETE /api/v1/upload-protection/rules/{id}", handlers.require(permissionWrite, handlers.deleteUploadProtectionRule))

	mux.HandleFunc("GET /api/v1/bot-protection/rules", handlers.require(permissionRead, handlers.listBotProtectionRules))
	mux.HandleFunc("POST /api/v1/bot-protection/rules", handlers.require(permissionWrite, handlers.createBotProtectionRule))
	mux.HandleFunc("GET /api/v1/bot-protection/rules/{id}", handlers.require(permissionRead, handlers.getBotProtectionRule))
	mux.HandleFunc("PUT /api/v1/bot-protection/rules/{id}", handlers.require(permissionWrite, handlers.updateBotProtectionRule))
	mux.HandleFunc("DELETE /api/v1/bot-protection/rules/{id}", handlers.require(permissionWrite, handlers.deleteBotProtectionRule))

	mux.HandleFunc("GET /api/v1/dynamic-protection/rules", handlers.require(permissionRead, handlers.listDynamicProtectionRules))
	mux.HandleFunc("POST /api/v1/dynamic-protection/rules", handlers.require(permissionWrite, handlers.createDynamicProtectionRule))
	mux.HandleFunc("GET /api/v1/dynamic-protection/rules/{id}", handlers.require(permissionRead, handlers.getDynamicProtectionRule))
	mux.HandleFunc("PUT /api/v1/dynamic-protection/rules/{id}", handlers.require(permissionWrite, handlers.updateDynamicProtectionRule))
	mux.HandleFunc("DELETE /api/v1/dynamic-protection/rules/{id}", handlers.require(permissionWrite, handlers.deleteDynamicProtectionRule))

	mux.HandleFunc("GET /api/v1/attack-protection/groups", handlers.require(permissionRead, handlers.listAttackProtectionGroups))
	mux.HandleFunc("PUT /api/v1/attack-protection/groups/{attack_type}", handlers.require(permissionWrite, handlers.updateAttackProtectionGroup))
}
